version: '3.3'
services:
    database:
        image: postgres:12
        volumes:
            - ./createUserDatabase:/docker-entrypoint-initdb.d/
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
    rest:
        command: sleep 600
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        depends_on: 
            - database
