package constants

const (
	WARRANTY_DECISION_RESUSE = "REFUSE"
	WARRANTY_DECISION_RETURN = "RETURN"
	WARRANTY_DECISION_FIXING = "FIXING"
	WARRANTY_STATUS_ON       = "ON_WARRANTY"
	WARRANTY_STATUS_USE      = "USE_WARRANTY"
	WARRANTY_STATUS_REMOVED  = "REMOVED_FROM_WARRANTY"
)
